# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-19 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rendition_filter_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrendition',
            name='filter',
        ),
    ]
